# Generated by Django 5.0.1 on 2024-01-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("temp", "Temp"),
                            ("old", "Old"),
                            ("billing", "Billing"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("postal", "Postal"),
                            ("physical", "Physical"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("line1", models.CharField(max_length=100)),
                ("line2", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=50)),
                ("begin_effective_datetime", models.DateTimeField()),
                ("end_effective_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ContactPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("fax", "Fax"),
                            ("email", "Email"),
                            ("pager", "Pager"),
                            ("url", "URL"),
                            ("sms", "SMS"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                ("use", models.CharField(max_length=10)),
                ("rank", models.PositiveSmallIntegerField()),
                ("begin_effective_datetime", models.DateTimeField()),
                ("end_effective_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="HumanName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        choices=[
                            ("usual", "Usual"),
                            ("official", "Official"),
                            ("temp", "Temp"),
                            ("nickname", "Nickname"),
                            ("anonymous", "Anonymous"),
                            ("old", "Old"),
                            ("maiden", "Maiden"),
                        ],
                        default="usual",
                        max_length=20,
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("family", models.CharField(max_length=50)),
                ("given", models.CharField(max_length=100)),
                ("prefix", models.CharField(max_length=50)),
                ("suffix", models.CharField(max_length=50)),
                ("begin_effective_datetime", models.DateTimeField()),
                ("end_effective_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use",
                    models.CharField(
                        choices=[
                            ("usual", "Usual"),
                            ("official", "Official"),
                            ("temp", "Temp"),
                            ("secondary", "Secondary"),
                            ("old", "Old"),
                        ],
                        default="usual",
                        max_length=20,
                    ),
                ),
                ("type_code", models.CharField(max_length=5)),
                ("type_system", models.CharField(max_length=50)),
                ("type_display", models.CharField(max_length=50)),
                ("system", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                ("begin_effective_datetime", models.DateTimeField()),
                ("end_effective_datetime", models.DateTimeField()),
                ("assigner", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("birth_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5)),
                ("system", models.CharField(max_length=50)),
                ("display", models.CharField(max_length=50)),
                ("begin_effective_datetime", models.DateTimeField()),
                ("end_effective_datetime", models.DateTimeField()),
                ("issuer", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PractitionerAddress",
            fields=[
                (
                    "address_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.address",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="api.practitioner",
                    ),
                ),
            ],
            bases=("api.address",),
        ),
        migrations.CreateModel(
            name="PractitionerContactPoint",
            fields=[
                (
                    "contactpoint_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.contactpoint",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_points",
                        to="api.practitioner",
                    ),
                ),
            ],
            bases=("api.contactpoint",),
        ),
        migrations.CreateModel(
            name="PractitionerName",
            fields=[
                (
                    "humanname_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.humanname",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="api.practitioner",
                    ),
                ),
            ],
            bases=("api.humanname",),
        ),
        migrations.CreateModel(
            name="PractitionerIdentifier",
            fields=[
                (
                    "identifier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.identifier",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="api.practitioner",
                    ),
                ),
            ],
            bases=("api.identifier",),
        ),
        migrations.CreateModel(
            name="QualificationIdentifier",
            fields=[
                (
                    "identifier_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.identifier",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="api.qualification",
                    ),
                ),
            ],
            bases=("api.identifier",),
        ),
    ]
